[section]

branch.all = """
git branch --all
"""

branch.list = """
git branch --list
"""

stash.show.remote = """
git branch --remotes
"""

stash.show.merge = """
git branch --merged
"""

stash.show.not.merge = """
git branch --no-merged
"""
