[section]

rsync.file = """
sudo rsync --verbose --archive --progress --stats /***/*.html /var/www/html
"""

rsync.dropbox = """
rsync --verbose --archive --progress --stats \
--exclude-from=.vscode/rsync_ignore.txt \
~/***/source/ \
~/***/destination/
"""
