[python.uv.add]

add = """
uv add ***
"""

add.package = """
uv add --package ***
"""

add.project = """
uv add --project packages/*** paramiko
"""

add.path = """
uv add dist/***-0.0.13-py3-none-any.whl
"""

add.test = """
uv add --project packages/*** *** --index test
"""
